import Footer from "@/components/store/common/footer";
import { Header } from "@/components/store/common/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "IW Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main className="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">{children}</main>
      <Footer />
    </>
  );
}
